name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - site-git-describe  # or whichever branch you're deploying from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run git describe and create version.js
      run: |
        GIT_DESCRIBE=$(git describe --tags --always)
        echo "document.addEventListener('DOMContentLoaded', function() {
            document.getElementById('version').textContent = '$GIT_DESCRIBE';
        });" > version.js

    - name: Upload artifact to be deployed
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./  # The directory containing your built site files

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        github_token: ${{ secrets.DIGITAL_SIGNAL_TOKEN }}
